sonar.projectKey=smms
sonar.projectName=SMMS
sonar.sourceEncoding=UTF-8

sonar.sources=api-gateway/src/main/java,customer-service/src/main/java,eureka-server/src/main/java,identity-service/src/main/java,inventory-service/src/main/java,notification-service/src/main/java,order-service/src/main/java,product-service/src/main/java,report-service/src/main/java,staff-service/src/main/java,smms-frontend/src
sonar.tests=api-gateway/src/test/java,customer-service/src/test/java,eureka-server/src/test/java,identity-service/src/test/java,inventory-service/src/test/java,notification-service/src/test/java,order-service/src/test/java,product-service/src/test/java,report-service/src/test/java,staff-service/src/test/java
sonar.java.binaries=api-gateway/target/classes,customer-service/target/classes,eureka-server/target/classes,identity-service/target/classes,inventory-service/target/classes,notification-service/target/classes,order-service/target/classes,product-service/target/classes,report-service/target/classes,staff-service/target/classes
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.mvn/**,uploads/**,test-data/**
sonar.test.inclusions=**/src/test/java/**
