export * as authApi from "./authApi"
export * as userApi from "./userApi"
export * as productApi from "./productApi"
export * as orderApi from "./orderApi"
export * as customerApi from "./customerApi"
export * as inventoryApi from "./inventoryApi"
export * as staffApi from "./staffApi"
export * as notificationApi from "./notificationApi"
export * as reportApi from "./reportApi"
export { default as api } from "./client"
